### ISSUE TITLE
Google App (android-app://com.google.android.googlequicksearchbox) not recognised as search engine

### ISSUE THREAD

**Issue by Joey3000** [piwik/searchengine-and-social-list#11]
This is a left-over from #3.

The "Google App" search (`android-app://com.google.android.googlequicksearchbox`) currently appears as referring website instead of a search engine.

Details and extraction example at https://firebase.google.com/docs/app-indexing/android/measure

Piwik appearance example: https://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2016-06-13#?module=Referrers&action=indexWebsites&idSite=7&period=day&date=2016-06-13

Piwik 2.6.1

**Comment by Joey3000** [comment]
Hi @sgiehl ! Just to make sure that this wasn't closed by mistake: What's the reason for closing this? (E.g., "already fixed", "won't be fixed", etc.) Thanks in advance!

**Comment by sgiehl** [comment]
It's fixed
