### ISSUE TITLE
Some URLs are not recognized as search engines

### ISSUE THREAD

**Issue by MichiMunich** [piwik/searchengine-and-social-list#23]
Hi,

with release 2.16.3 i have a few sites listed as referring websites instead of search engines:

- [x] [www.ixquick.com](url)
- [x] [www.ixquick.de](url)
- [x] [ixquick.com](url)
- [x] [search.avira.net](url)
- [x] [search.f-secure.com](url)
- [x] [www.startpage.com](url)
- [x] [startpage.com](url)
- [x] [eu.startpage.com](url)
- [x] [s2-eu4.startpage.com](url)
- [x] [s6-eu5.ixquick.com](url)
- [x] [s7-eu4.startpage.com](url)
- [x] [s8-eu5.startpage.com](url)
- [x] [s11-eu5.startpage.com](url)
- [x] [s12-eu5.startpage.com](url)
- [x] [s13-eu5.startpage.com](url)

**Comment by sgiehl** [comment]
All mentioned engines should be detected now. If not please open new issues.
