### ISSUE TITLE
some of the urls are offline

### ISSUE THREAD

**Issue by Findus23** [piwik/searchengine-and-social-list#28]
While trying to update all icons in Piwik (https://github.com/piwik/piwik/pull/11063), I realized that many of the urls in the list don't exist anymore.

# Socials
- [x] http://t.cn  HTTPConnectionPool(host='t.cn', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8cbe602ef0>, 'Connection to t.cn timed out. (connect timeout=15)'))
- [x] http://identi.ca  HTTPConnectionPool(host='identi.ca', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8cbfc348d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
- [x] http://douban.com  HTTPConnectionPool(host='www.douban.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8cbe602470>, 'Connection to www.douban.com timed out. (connect timeout=15)'))
- [x] http://global.cyworld.com  HTTPConnectionPool(host='global.cyworld.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8cbe604ef0>, 'Connection to global.cyworld.com timed out. (connect timeout=15)'))
- [x] http://myyearbook.com  403 Client Error: Forbidden for url: http://myyearbook.com/
- [x] http://url.google.com  HTTPConnectionPool(host='url.google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8cbfc1dd68>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
- [x] http://mylife.ru  HTTPConnectionPool(host='mylife.ru', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7f8cbda90c18>, 'Connection to mylife.ru timed out. (connect timeout=15)'))

# Search Engines
- [x] http://search.fbdownloader.com  HTTPConnectionPool(host='search.fbdownloader.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fdece689b38>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
- [x] http://busca.orange.es  HTTPConnectionPool(host='busca.orange.es', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fbbe0>, 'Connection to busca.orange.es timed out. (connect timeout=15)'))
- [x] http://gais.cs.ccu.edu.tw  HTTPConnectionPool(host='gais.cs.ccu.edu.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6feda0>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
- [x] http://search.freecause.com  HTTPConnectionPool(host='search.freecause.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ccac8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://www.blogpulse.com  HTTPConnectionPool(host='www.blogpulse.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0cc748>, 'Connection to www.blogpulse.com timed out. (connect timeout=15)'))
- [x] http://ko.search.need2find.com  HTTPConnectionPool(host='ko.search.need2find.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ca0b8>, 'Connection to ko.search.need2find.com timed out. (connect timeout=15)'))
- [x] http://www.gomeo.com  HTTPConnectionPool(host='www.gomeo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6f0b00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
- [x] http://verden.abcsok.no  404 Client Error: Not Found for url: http://www.startsiden.no/sok/google/../
- [x] http://arama.com  Timeout
- [x] http://bg.setooz.com  HTTPConnectionPool(host='bg.setooz.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fb940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://da.setooz.com  HTTPConnectionPool(host='da.setooz.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fb940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://el.setooz.com  HTTPConnectionPool(host='el.setooz.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fb940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://fa.setooz.com  HTTPConnectionPool(host='fa.setooz.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fb940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://ur.setooz.com  HTTPConnectionPool(host='ur.setooz.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fb4e0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://morfeo.centrum.cz  410 Client Error: Gone for url: http://morfeo.centrum.cz/
- [x] http://sp-image.search.auone.jp  HTTPConnectionPool(host='sp-image.search.auone.jp', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fbe10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://www.blogdigger.com  HTTPConnectionPool(host='www.blogdigger.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ccef0>, 'Connection to www.blogdigger.com timed out. (connect timeout=15)'))
- [x] http://www.toolbarhome.com  HTTPConnectionPool(host='www.toolbarhome.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ca7f0>, 'Connection to www.toolbarhome.com timed out. (connect timeout=15)'))
- [x] http://vshare.toolbarhome.com  HTTPConnectionPool(host='vshare.toolbarhome.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fe0b8>, 'Connection to vshare.toolbarhome.com timed out. (connect timeout=15)'))
- [x] http://googlesyndicatedsearch.com  HTTPConnectionPool(host='googlesyndicatedsearch.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ca4e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
- [x] http://www.trouvez.com  HTTPConnectionPool(host='www.trouvez.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0cac18>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
- [x] http://fr.dir.com  HTTPConnectionPool(host='fr.dir.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ce1d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://www.vindex.nl  HTTPConnectionPool(host='www.vindex.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fe080>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
- [x] http://search.vindex.nl  HTTPConnectionPool(host='search.vindex.nl', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6febe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
- [x] http://s1.metacrawler.de  HTTPConnectionPool(host='s1.metacrawler.de', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fe048>: Failed to establish a new connection: [Errno 111] Connection refused',))
- [x] http://s3.metacrawler.de  HTTPConnectionPool(host='s3.metacrawler.de', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fb8d0>, 'Connection to s3.metacrawler.de timed out. (connect timeout=15)'))
- [x] http://search.smartshopping.com  HTTPConnectionPool(host='search.smartshopping.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fe128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://www.toile.com  ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
- [x] http://search.altavista.com  HTTPConnectionPool(host='search.altavista.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6f0d68>: Failed to establish a new connection: [Errno -2] Name or service not known',))
http://forestle.mobi  HTTPConnectionPool(host='forestle.mobi', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6fb8d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://search.bluewin.ch  HTTPConnectionPool(host='search.bluewin.ch', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0d1780>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
- [x] http://ms114.mysearch.com  HTTPConnectionPool(host='ms114.mysearch.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6f0860>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
- [x] http://ms146.mysearch.com  HTTPConnectionPool(host='ms146.mysearch.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6f0898>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
- [x] http://kf.mysearch.myway.com  HTTPConnectionPool(host='kf.mysearch.myway.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1b6f0e48>, 'Connection to kf.mysearch.myway.com timed out. (connect timeout=15)'))
- [x] http://ki.mysearch.myway.com  HTTPConnectionPool(host='ki.mysearch.myway.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0d1668>, 'Connection to ki.mysearch.myway.com timed out. (connect timeout=15)'))
- [x] http://www.123people.com  410 Client Error: Gone for url: http://www.123people.com/
- [x] http://www1.baidu.com  404 Client Error: Not Found for url: http://www1.baidu.com/
- [x] http://www.baidu.co.th  HTTPConnectionPool(host='www.baidu.co.th', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ce2b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://int.ask.com  HTTPConnectionPool(host='int.ask.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0d9c50>, 'Connection to int.ask.com timed out. (connect timeout=15)'))
- [x] http://ask.reference.com  410 Client Error: Gone for url: http://ask.reference.com/information
- [x] http://iwon.ask.com  HTTPConnectionPool(host='iwon.ask.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ca978>, 'Connection to iwon.ask.com timed out. (connect timeout=15)'))
- [x] http://www.qbyrd.com  HTTPConnectionPool(host='www.qbyrd.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0dee10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://www2.google.com  HTTPConnectionPool(host='www2.google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0cc9e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [X] http://ipv6.google.com  HTTPConnectionPool(host='ipv6.google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ce6a0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

*I don't have a IPv6 Connection*
- [x] http://go.google.com  HTTPConnectionPool(host='go.google.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ca2e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://gppgle.com  404 Client Error: Not Found for url: http://gppgle.com/
- [x] http://com.google.android.googlequicksearchbox  HTTPConnectionPool(host='com.google.android.googlequicksearchbox', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0ca128>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://www.trusted-search.com  HTTPConnectionPool(host='www.trusted-search.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fbd1a0cef60>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://mamma75.mamma.com  HTTPSConnectionPool(host='mamma75.mamma.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f128f3ceb00>: Failed to establish a new connection: [Errno 111] Connection refused',))
- [x] http://holmes.ge  HTTPConnectionPool(host='holmes.ge', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f940d131940>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://lo.st  HTTPConnectionPool(host='lo.st', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f940d131a20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
- [x] http://claro-search.com  HTTPConnectionPool(host='claro-search.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f940d13cb38>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))
- [x] http://www.eu.ixquick.com  HTTPConnectionPool(host='www.eu.ixquick.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f940d13c9b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://s1.us.ixquick.com  HTTPConnectionPool(host='s1.us.ixquick.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f940bb0b6a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://s2.us.ixquick.com  HTTPConnectionPool(host='s2.us.ixquick.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f940bb0b6a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://s3.us.ixquick.com  HTTPConnectionPool(host='s3.us.ixquick.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f940bb0b6a0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://s4.us.ixquick.com  HTTPConnectionPool(host='s4.us.ixquick.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f940bb0b9e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://s5.us.ixquick.com  HTTPConnectionPool(host='s5.us.ixquick.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f940bb0b780>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://videosearch.nifty.com  404 Client Error: Not Found for url: http://videosearch.nifty.com/
- [x] http://extern.peoplecheck.de  hostname 'extern.peoplecheck.de' doesn't match either of 'handelsregisterauszug.peoplecheck.de', 'peoplecheck.de', 'ssl.peoplecheck.de'
- [x] http://recherche.francite.com  HTTPConnectionPool(host='recherche.francite.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe041974828>, 'Connection to recherche.francite.com timed out. (connect timeout=15)'))
- [x] http://chercherfr.aguea.com  HTTPConnectionPool(host='chercherfr.aguea.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe041971da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://www.latne.lv  412 Client Error: Precondition Failed for url: http://www.latne.lv/
- [x] http://www.zxuso.com  Timeout
- [x] http://fr.wedoo.com  HTTPConnectionPool(host='fr.wedoo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe041971518>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://en.wedoo.com  HTTPConnectionPool(host='en.wedoo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe041971278>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://es.wedoo.com  HTTPConnectionPool(host='es.wedoo.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe041971eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://search.yippy.com  HTTPConnectionPool(host='search.yippy.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe041971160>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://searchalot.com  403 Client Error: Forbidden for url: http://searchalot.com/
- [x] http://web.canoe.ca  HTTPConnectionPool(host='web.canoe.ca', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe0419718d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
- [x] http://junglekey.com  403 Client Error: Forbidden for url: http://junglekey.com/
- [x] http://junglekey.fr  403 Client Error: Forbidden for url: http://junglekey.fr/
- [x] http://www.cuil.com  HTTPConnectionPool(host='www.cuil.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe040340668>: Failed to establish a new connection: [Errno -2] Name or service not known',))
- [x] http://eo.st  HTTPConnectionPool(host='eo.st', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe040340da0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
- [x] http://www.abacho.com  HTTPConnectionPool(host='www.abacho.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff1734ea160>, 'Connection to www.abacho.com timed out. (connect timeout=15)'))
- [x] http://www.abacho.co.uk  HTTPConnectionPool(host='www.abacho.co.uk', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff1734f4978>, 'Connection to www.abacho.co.uk timed out. (connect timeout=15)'))
- [x] http://www.se.abacho.com  HTTPConnectionPool(host='www.se.abacho.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff1734f7550>, 'Connection to www.se.abacho.com timed out. (connect timeout=15)'))
- [x] http://www.tr.abacho.com  HTTPConnectionPool(host='www.tr.abacho.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff1734f4b38>, 'Connection to www.tr.abacho.com timed out. (connect timeout=15)'))
- [x] http://www.abacho.at  HTTPConnectionPool(host='www.abacho.at', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff1734ed128>, 'Connection to www.abacho.at timed out. (connect timeout=15)'))
- [x] http://www.abacho.es  HTTPConnectionPool(host='www.abacho.es', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff1734ea828>, 'Connection to www.abacho.es timed out. (connect timeout=15)'))
- [x] http://www.abacho.ch  HTTPConnectionPool(host='www.abacho.ch', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff171ec3358>, 'Connection to www.abacho.ch timed out. (connect timeout=15)'))
- [x] http://brisbane.t-online.de  hostname 'brisbane.t-online.de' doesn't match 'suche.t-online.de'
- [x] http://1.cz  HTTPConnectionPool(host='1.cz', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff54d19dc18>, 'Connection to 1.cz timed out. (connect timeout=15)'))

**Comment by istana** [comment]
At least identi.ca works now - but the error was connection refused and not connect timeout.

I don't know much about other items, but *com.google.android.googlequicksearchbox* has origin in Android (is it legit?), other domains had only temporary problems. How about historic value of search engines for statistics purposes?

**Comment by Findus23** [comment]
@istana You are right, identica.ca is online again.
`com.google.android.googlequicksearchbox` is an error of my script as is not a domain but an android app.

I didn't mean, that these domains should be removed from piwik. It was just a side effect of my attempt of updating all piwik icons, that I didn't want to keep to myself.

**Comment by istana** [comment]
thanks for sharing your findings, it's certainly useful to know that so many search engines or bots are probably dead

**Comment by sgiehl** [comment]
I'm not sure if we should remove those "dead" ones from the list, as they might still be relevant when analyzing historical data.

**Comment by Findus23** [comment]
Now that all pages have icons, this doesn't really matter any more.
