### ISSUE TITLE
Search engines not recognized in 2.16.1: HTTPS, non-HTTPS, and a special Android one

### ISSUE THREAD

**Issue by endrepalinkas** [piwik/searchengine-and-social-list#3]
Hi,

Here are a bunch referring URLs that aren't recognized as search engines in Piwik 2.6.1, and they should be probably.

**HTTPS referrer search engines:**
- [x] https://search.yahoo.com/
- [x] https://www.bing.com/
- [x] https://search.bt.com/result?channel=btfon&p=example+query
- [x] https://www.google.ru/search
- [x] https://www.google.co.id/search
- [x] https://cse.google.com/cse?hl=tr&cx=partner-pub-7724398453132474:uo00y3f33s4&q=example+query&sa=Google%27da+Ara&ie=utf-8
- [x] https://cse.google.com/cse?cx=010720650476917319035:grbfmxha2ng&sa=Search&cof=FORID:0&ie=utf-8&oe=utf-8&q=example+query
- [x] https://search.disconnect.me/searchTerms/serp?search=d7c00246-73e3-438d-b933-560bcfe91110
- [x] https://us.search.yahoo.com/
- [x] https://ca.search.yahoo.com/
- [x] https://au.search.yahoo.com/
- [x] https://malaysia.search.yahoo.com/
- [x] https://safesearch.avira.com/
- [x] https://search.avast.com/AV772/search/web?qsi=21&q=example%query&fcoid=4&fcop=results-bottom&fpid=2
- [x] https://startpage.com/do/search
- [x] https://www.searchlock.com/
- [x] https://www.qwant.com/

**And some-non HTTP while at it:**
- [x] http://search.yahoo.co.jp/
- [x] http://search.zum.com/search.zum?method=web&option=accu&query=examplequery&cm=more
- [x] http://startgoogle.startpagina.nl/?start=20&query=example+query&num=10&ts=ts2&origin=homepage&tab=internet
- [x] http://govome.inspsearch.com/search/web?qsi=11&q=example%20query&p=2&fcoid=4&fcop=bottomnav&fpid=2
- [x] http://jwsearch.jword.jp/search?q=examplequery&act=web&pvs=e-start-search-box&inec=utf-8&per_page=2
- [x] http://search.lookseek.com/search2.php?q=example%20query&start=41
- [x] http://msxml.excite.com/search/web?qsi=61&q=example%20query&p=7&fcoid=4&fcop=bottomnav&fpid=2
- [x] http://startab.me/search/?q=example%20query
- [x] http://www.only-search.com/?s=web&babsrc=HP_tedge&affID=130425&rlz=0&sd=61&q=example+query&start=90
- [x] http://cse.google.com/cse?cx=016950229825784542350:bzwdloke61c&q=examplequery&oq=examplequery&gs_l=partner.12...19296.25489.0.27512.8.8.0.0.0.0.476.2449.1j0j2j4j1.8.0.gsnos,n=13...0.6279j7232129j8..1ac.1.25.partner..7.1.374.nF4pSwcnzCk

**And a new special one that just started appearing:**
- [ ] android-app://com.google.android.googlequicksearchbox

**Comment by sgiehl** [comment]
Need to have a close look at the list. Are you really using Piwik 2.6.1 ? Maybe some of them are now already detected then.

**Comment by endrepalinkas** [comment]
Thanks @sgiehl ! 

Sorry, it's 2.16.1 of course :)

**Comment by Joey3000** [comment]
> And a new special one that just started appearing:
> android-app://com.google.android.googlequicksearchbox

Details and extraction example at https://firebase.google.com/docs/app-indexing/android/measure

Piwik appearance example: https://demo.piwik.org/index.php?module=CoreHome&action=index&idSite=7&period=day&date=2016-06-13#?module=Referrers&action=indexWebsites&idSite=7&period=day&date=2016-06-13

**Comment by mattab** [comment]
Hi @Joey3000 it's appreciated if you can create a separate issue so we don't forget about this one

**Comment by Joey3000** [comment]
Hi, @mattab. Done: #11

**Comment by mattab** [comment]
@sgiehl maybe this one can be closed?

**Comment by sgiehl** [comment]
yes, can be closed :)
