### ISSUE TITLE
mail.ru is not defined as a search engine

### ISSUE THREAD

**Issue by FatPuzo** [piwik/searchengine-and-social-list#39]
Hello. Mail.ru besides open keyword now has encoded one. Referrer looks like this: http://go.mail.ru/redir?via_page=1&type=sr&redir=pretty_long_string_goes_Here
And this referrer is note defined as a search engine.

**Comment by sgiehl** [comment]
Are you sure this is a referrer from the mail.ru search engine? Can you post a link to a result page on that such links are shown?

**Comment by FatPuzo** [comment]
For example: https://go.mail.ru/search?fr=main&sbmt=1511509532829&frm=main&q=Упражнения+с+гантелями+для+детей.

If you copy on of the links with mouth's right button you'll see the real link, that looks like I gave before.

**Comment by sgiehl** [comment]
Thanks
