### ISSUE TITLE
Other search engines

### ISSUE THREAD

**Issue by Zefling** [piwik/searchengine-and-social-list#9]
Currently not supported : 
- [x] http://lemoteur.orange.fr/?kw=test 
- [x] https://fr.search.yahoo.com/?p=test 
- [x] https://ca.search.yahoo.com/?p=test 
- [x] https://search.yahoo.co.jp/search?p=test 
- [ ] https://lite.qwant.com/?q=test

**Comment by sgiehl** [comment]
The yahoo host weren't detected without keywords. That was fixed in https://github.com/piwik/piwik/commit/714f7c13849267707cab7c72539c33437858a11c
I'll have a look at the other two.
